config/routes.rb
Progcomp::Application.routes.draw do

  root :to => 'competitions#index'

  resources :competitions do
    resources :teams, :problems
  end

  devise_for :users
  resources :team_members

end

app/models/competition.rb
class Competition < ActiveRecord::Base
  attr_accessible :end_time, :name, :start_time
  has_many :teams, :dependent => :destroy
  has_many :problems, :dependent => :destroy

  def default
    #returns the closest competition that has not ended yet
    comps = Competition.all
    comps.sort_by! {|comp| comp.end_time }
    now = Time.now
    comps.each do |comp|
      return comp if comp.end_time > now
    end
  end
  def header_problems
    pbs = problems
    pbs.delete_if {|pb| not pb.parent_id.nil?}
    return pbs.sort_by {|pb| pb.number }
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @competitions }
    end
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    @competition = Competition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @competition }
    end
  end

  # GET /competitions/new
  # GET /competitions/new.json
  def new
    @competition = Competition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @competition }
    end
  end

  # GET /competitions/1/edit
  def edit
    @competition = Competition.find(params[:id])
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(params[:competition])

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render json: @competition, status: :created, location: @competition }
      else
        format.html { render action: "new" }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /competitions/1
  # PUT /competitions/1.json
  def update
    @competition = Competition.find(params[:id])

    respond_to do |format|
      if @competition.update_attributes(params[:competition])
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy

    respond_to do |format|
      format.html { redirect_to competitions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<h1>Listing competitions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start time</th>
    <th>End time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @competitions.each do |competition| %>
  <tr>
    <td><%= competition.name %></td>
    <td><%= competition.start_time %></td>
    <td><%= competition.end_time %></td>
    <td><%= link_to 'Show', competition %></td>
    <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
    <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Competition', new_competition_path %>

app/views/competitions/new.html.erb
<h1>New competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @competition.name %>
</p>

<p>
  <b>Start time:</b>
  <%= @competition.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @competition.end_time %>
</p>

<p> <%= link_to 'Edit', edit_competition_path(@competition) %> |
  <%= link_to 'Back', competitions_path %> </p>

<p> <%= link_to 'Problems', competition_problems_path(@competition) %> |
  <%= link_to 'Teams', competition_teams_path(@competition) %> </p>