config/routes.rb
Progcomp::Application.routes.draw do

  root :to => 'competitions#index'

  resources :competitions do
    resources :teams, :problems
  end

  devise_for :users
  resources :team_members

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :competition
  belongs_to :parent, :class_name => "Problem"
  has_many :subproblems, :class_name => "Problem", :foreign_key => "parent_id", :dependent => :destroy
  has_many :solutions
  attr_accessible :number, :point, :solution, :solution_type, :text, :title, :parent_id
  def total_points
    pt = point
    subs = subproblems
    subs.each do |sub|
      pt += sub.point
    end
    return pt
  end
  def parent_top
    p = self
    until p.parent.nil?
      p = p.parent
    end
    return p
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_filter :get_competition
  # GET /problems
  # GET /problems.json
  def index
    @problems = @competition.header_problems
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = @competition.problems.build()
    @problem.parent_id = params[:parent_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = @competition.problems.build(params[:problem])

    respond_to do |format|
      if @problem.save
        format.html { redirect_to competition_problem_url(@competition, @problem.parent_top), notice: 'Problem was successfully created.' }
        format.json { render json: @problem, status: :created, location: @problem }
      else
        format.html { render action: "new" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.find(params[:id])

    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to competition_problem_url(@competition, @problem), notice: 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    parent = @problem.parent
    @problem.destroy

    respond_to do |format|
      format.html do
        redirect_to :back
      end
      format.json { head :no_content }
    end
  end
  def get_competition
    @competition = Competition.find(params[:competition_id])
    #|| Competition.default  -- TODO this doesn't work with routes conf as of now
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_form.html.erb
<%= form_for([@problem.competition, @problem]) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :parent_id %>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :solution %><br />
    <%= f.text_field :solution %>
  </div>
  <div class="field">
    <%= f.label :solution_type %><br />
    <%= f.text_field :solution_type %>
  </div>
  <div class="field">
    <%= f.label :point %><br />
    <%= f.number_field :point %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/_problem.html.erb
<div class = 'subproblem'>
<h4> <%= "#{problem.number}. #{problem.title}" %> </h4>

<p>
  <%= problem.text %>
  <%= link_to 'Edit', edit_competition_problem_path(problem.competition, problem) %>
  <%= link_to 'Remove', [problem.competition, problem], confirm: 'Are you sure?', method: :delete %>
</p>

<%= render :partial => "solutions/solve", :locals => { :problem => problem } %>

<%= render problem.subproblems %>

</div>

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', competition_problem_path(@competition, @problem.parent_top) %> |
<%= link_to 'Back', competition_problems_path(@competition, @problem.parent_top) %>

app/views/problems/index.html.erb
<h1>Listing problems</h1>

<table>

<% @problems.each do |problem| %>
  <tr>
    <td><b><%= link_to "#{problem.number} #{problem.title}", competition_problem_path(@competition, problem) %></b></td>
    <td><%= problem.text %></td>
    <td><%= problem.total_points %> points </td>
    <td><%= link_to 'Edit', edit_competition_problem_path(@competition, problem) %></td>
    <td><%= link_to 'Remove', [problem.competition, problem], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Problem', new_competition_problem_path(@competition) %>

app/views/problems/new.html.erb
<h1>New problem</h1>

<%= render 'form' %>

<% if @problem.parent.nil? %>
<%= link_to 'Back', competition_problems_path(@competition) %>
<% else %>
<%= link_to 'Back', competition_problem_path(@competition, @problem.parent_top) %>
<% end %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= "#{@problem.number}. #{@problem.title}" %> </h1>

<p>
  <%= @problem.text %>
  <%= link_to 'Edit', edit_competition_problem_path(@competition, @problem) %>

</p>

<%= render :partial => "solutions/solve", :locals => { :problem => @problem } %>
<%= link_to 'Add Subproblem', new_competition_problem_path(@competition, :parent_id => @problem.id) %>
<%= render @problem.subproblems.sort_by{|sub| sub.number} %>

<%= link_to 'Back', competition_problems_path(@competition) %>